---
- name: Creates directory for maven
  file:
    path: /opt/maven
    state: directory
    mode: 0755

- name: Download and unarchive Maven
  unarchive:
    src: http://apache.uib.no/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
    dest: /opt/maven
    remote_src: yes
    creates: /opt/maven/apache-maven-3.5.2/bin/mvn

- name: Add Maven to PATH globally for all users
  template:
    src: maven.sh.j2
    dest: /etc/profile.d/maven.sh
    mode: 0644